[tool.mypy]
python_version = "3.13"
show_error_codes = true
follow_imports = "silent"
ignore_missing_imports = true
strict_equality = true
warn_incomplete_stub = true
warn_redundant_casts = true
warn_unused_configs = true
check_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
no_implicit_optional = true
warn_return_any = true
warn_unreachable = true

[tool.pytest.ini_options]
testpaths = "tests"
norecursedirs = ".git"
asyncio_mode = "auto"

[tool.ruff]
line-length = 100
target-version = "py313"
extend-exclude = ["tests/stubs"]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"custom_components/unifi_gateway_refactored/sensor.py" = [
    "C901",
    "D101",
    "D102",
    "D103",
    "D107",
]
"custom_components/unifi_gateway_refactored/unifi_client.py" = [
    "C901",
    "D102",
    "D103",
]

[tool.ruff.lint.isort]
known-first-party = ["custom_components.unifi_gateway_refactored"]