class RequestException(Exception): ...


class HTTPError(RequestException): ...


class ConnectionError(RequestException): ...


class Timeout(RequestException): ...


class TooManyRedirects(RequestException): ...
